wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698686544.331955
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 1
      - 2
      - 23
      4: 3.11.0
      5: 0.15.12
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
